#!/usr/bin/env bash
CLI_DIR=$(dirname $0)
WORKING_DIR='../TEST'
source $CLI_DIR/common.sh
NAME=$1
IMAGE=$2
HOST=${3:-'registry001'}

_start=`date +%s`

publishImage $NAME $IMAGE $HOST

_end=`date +%s`

_secs=$((_end-_start))
printf '** Total %s\n' $(printTime $_start $_end)

# publish app-pod b3424ddb2227 registry001