#!/usr/bin/env bash
CLI_DIR=$(dirname $0)
WORKING_DIR='../TEST'
source $CLI_DIR/common.sh
REGISTRY=$1
IMAGE=$2

_start=`date +%s`

listImages $REGISTRY

_end=`date +%s`

_secs=$((_end-_start))
printf '** Total %s\n' $(printTime $_start $_end)